services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5

  web:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,162.243.42.209,*"
      OLLAMA_BASE_URL: "http://ollama:11434"
    volumes:
      - ./theme:/app/theme
      - static_volume:/app/staticfiles
    command: >
      sh -c "./wait-for-db.sh db 3306 && 
             mkdir -p /app/static &&
             python manage.py migrate && 
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 roro_ai.wsgi:application --workers 3"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - web
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:8000"

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11435:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  db_data:
  ollama_data:
  static_volume:
