# Generated by Django 5.2 on 2025-04-26 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coder", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codeinteraction",
            options={},
        ),
        migrations.AlterModelOptions(
            name="codesession",
            options={},
        ),
        migrations.AlterField(
            model_name="codeinteraction",
            name="code_snippet",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="codesession",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="codesession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
